export const PRODUCTS_ACTION_TYPES = {
    SET_PRODUCTS: 'products/SET_PRODUCTS',
    GET_PRODUCTS_START: 'products/GET_PRODUCTS_START',
    GET_PRODUCTS_SUCCESS: 'products/GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'products/GET_PRODUCTS_FAILURE',
}